services:
  api.public:
    image: api.public
    hostname: api-public
    restart: on-failure
    ports:
      - 8080:8080
      - 4443:4443
    build:
      context: ../Api.Public
      dockerfile: "Dockerfile.Local"
    depends_on:
      - clamav
    volumes:
      - ../:/root/.dotnet/https
    networks:
      - network

  clamav: 
    image: clamav/clamav
    hostname: clamav
    ports:
      - 3310:3310
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
